=== hexereii/BerryHUD/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "description": "Display name of your HUD",
      "type": "string"
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string"
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releaseDate": {
      "description": "Initial release date of the HUD",
      "type": "string"
    },
    "social": {
      "description": "Links to your social media profiles",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string"
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string"
        },
        "steam_group": {
          "description": "Your Steam group",
          "type": "string"
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string"
        },
        "discord": {
          "description": "Your Discord invite code, not the full URL",
          "type": "string"
        },
        "youtube": {
          "description": "Your YouTube channel (either /channel/id URL, @username or channel name)",
          "type": "string"
        },
        "twitch": {
          "description": "Your Twitch channel name",
          "type": "string"
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string"
        }
      }
    },
    "flags": {
      "description": "A list of boolean flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "1/1",
              "4/3",
              "5/4",
              "16/10",
              "16/9",
              "17/9",
              "21/9",
              "32/9"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      }
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repo": {
      "description": "GitHub repo web URL",
      "type": "string"
    },
    "hash": {
      "description": "Git commit hash of your current version (PR an update to this each time your HUD updates, and we will approve it)",
      "type": "string"
    },
    "prerelease": {
      "description": "If this is a prerelease/WIP HUD",
      "type": "boolean"
    },
    "verified": {
      "description": "For internal use only to enable some functionality. Do not set this yourself.",
      "type": "boolean"
    },
    "parent": {
      "description": "If this HUD is a slight edit of another, put its ID here. This will group the HUDs together.",
      "type": "string"
    },
    "resources": {
      "description": "A list of image names/YouTube videos. Images are automatically converted to webp, do not use extensions for uploaded images",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true
    }
  }
}

=== hexereii/BerryHUD/hud-data/evolve-hud.json
{
  "name": "Evolve HUD",
  "author": "Eevove",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/C9Ij8"
  },
  "repo": "https://github.com/Hypnootize/Evolve-Hud",
  "hash": "a5c7e157925c4871403b371d7d76f8f56dc12a5d",
  "resources": [
    "evolve-hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/m0re-hypnotize.json
{
  "name": "m0re Hypnotize",
  "author": "Hypnotize",
  "social": {
    "steam_profile": "76561198058754493",
    "album": "http://imgur.com/a/2gckG"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ],
    "position": [
      "center"
    ],
    "lang": [
      "en"
    ]
  },
  "repo": "https://github.com/Hypnootize/Hypnotize-m0rehud",
  "hash": "e392a7a1e075674d27eab917f60d4b955e767d6f",
  "parent": "m0rehud",
  "resources": [
    "m0rehypnotize-banner",
    "m0rehypnotize-menu",
    "m0rehypnotize-loadout",
    "m0rehypnotize-backpack",
    "m0rehypnotize-classselection",
    "m0rehypnotize-buff",
    "m0rehypnotize-hurt",
    "m0rehypnotize-minmode",
    "m0rehypnotize-engineer",
    "m0rehypnotize-scoreboard",
    "m0rehypnotize-spectator"
  ]
}

=== hexereii/BerryHUD/hud-data/grape-m0re.json
{
  "name": "Grape-m0re",
  "author": "Grape",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/8KYR6"
  },
  "repo": "https://github.com/Hypnootize/Grape-M0rehud",
  "hash": "35021987433152dc5f785f4f0759cb15abb169dd",
  "parent": "m0rehud",
  "resources": [
    "grape-m0re-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/7hud.json
{
  "name": "7HUD",
  "author": "sevin",
  "social": {
    "steam_profile": "76561198056804798",
    "steam_group": "7HUD",
    "album": "https://imgur.com/a/yluqH"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "mac",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "16/9"
    ]
  },
  "repo": "https://github.com/Sevin7/7hud",
  "hash": "474914eceb324d77296831824e4cc7dc484d0a1f",
  "resources": [
    "7hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/rain-hud.json
{
  "name": "Rain HUD",
  "author": "RainofLight",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/CZrFj"
  },
  "repo": "https://github.com/Hypnootize/Rain-Hud",
  "hash": "873d01fe31c9a05d1af3b76c95d15b69abd3a21b",
  "resources": [
    "rain-hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/garm3n-8mg.json
{
  "name": "Garm3n 8MG",
  "author": "Garm3n",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/0Mn7x"
  },
  "repo": "https://github.com/Hypnootize/Garm3n-8MG",
  "hash": "d2b19bd2e94205ed40256c4b61e7d9595e798b7b",
  "parent": "quakehud",
  "resources": [
    "garm3n-8mg-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/g-mang-hud.json
{
  "name": "G-Mang HUD",
  "author": "G-Mang",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "gmanghud",
    "album": "https://imgur.com/a/IZKZA"
  },
  "repo": "https://github.com/Hypnootize/G-Mang-Hud",
  "hash": "52fe314fdaadd926129fb9f105209d1850c5ea7c",
  "resources": [
    "g-mang-hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/sammyhud.json
{
  "name": "sammyhud",
  "author": "sammy",
  "social": {
    "album": "https://imgur.com/a/P0DQaBe"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pl",
      "plr",
      "pd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "16/9"
    ]
  },
  "repo": "https://github.com/sammybun/sammyhud",
  "hash": "671c8d85c6e287cf3e4c038635aeba92c036baa6",
  "resources": [
    "sammyhud-banner"
  ]
}
