=== hexereii/BerryHUD/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "description": "Display name of your HUD",
      "type": "string"
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string"
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releaseDate": {
      "description": "Initial release date of the HUD",
      "type": "string"
    },
    "social": {
      "description": "Links to your social media profiles",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string"
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string"
        },
        "steam_group": {
          "description": "Your Steam group",
          "type": "string"
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string"
        },
        "discord": {
          "description": "Your Discord invite code, not the full URL",
          "type": "string"
        },
        "youtube": {
          "description": "Your YouTube channel (either /channel/id URL, @username or channel name)",
          "type": "string"
        },
        "twitch": {
          "description": "Your Twitch channel name",
          "type": "string"
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string"
        }
      }
    },
    "flags": {
      "description": "A list of boolean flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "1/1",
              "4/3",
              "5/4",
              "16/10",
              "16/9",
              "17/9",
              "21/9",
              "32/9"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      }
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repo": {
      "description": "GitHub repo web URL",
      "type": "string"
    },
    "hash": {
      "description": "Git commit hash of your current version (PR an update to this each time your HUD updates, and we will approve it)",
      "type": "string"
    },
    "prerelease": {
      "description": "If this is a prerelease/WIP HUD",
      "type": "boolean"
    },
    "verified": {
      "description": "For internal use only to enable some functionality. Do not set this yourself.",
      "type": "boolean"
    },
    "parent": {
      "description": "If this HUD is a slight edit of another, put its ID here. This will group the HUDs together.",
      "type": "string"
    },
    "resources": {
      "description": "A list of image names/YouTube videos. Images are automatically converted to webp, do not use extensions for uploaded images",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true
    }
  }
}

=== hexereii/BerryHUD/hud-data/yahud-mx.json
{
  "name": "Yahud MX",
  "author": "Whayay",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/59N9S"
  },
  "repo": "https://github.com/Hypnootize/Yahud-M-X",
  "hash": "c779a19d93ff3934d465541918cb91942ae270bf",
  "parent": "yayahud",
  "resources": [
    "yahud-mx-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/med-hud.json
{
  "name": "medHUD",
  "author": "intel",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "medhud",
    "album": "https://imgur.com/a/1ufBE"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/Hypnootize/medHUD",
  "hash": "a8afa58261ea680e1b59b86a8871654cb28a0244",
  "resources": [
    "med-hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/wavesui.json
{
  "name": "Wavesui",
  "author": "extracrispy",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/Xxxoc"
  },
  "repo": "https://github.com/Hypnootize/Wavesui-Hud",
  "hash": "663021acedb4c0a26cb9374a45e1e4eb90ea8116",
  "resources": [
    "wavesui-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/zonahud.json
{
  "name": "ZONAhud",
  "author": "Lardox",
  "social": {
    "album": "https://imgur.com/a/ehRvn8z"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "16/9"
    ]
  },
  "repo": "https://github.com/tf2huds/zonahud",
  "hash": "633ec34e176a36197230e95240325782d9114adf",
  "resources": [
    "zonahud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/xhud.json
{
  "name": "Xhud",
  "author": "Peaches",
  "social": {
    "support": "https://ko-fi.com/peachestv",
    "discord": "HyZRVtp",
    "youtube": "@PeachesFPS",
    "twitch": "peachestv"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "pl",
      "plr",
      "pd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/10",
      "16/9"
    ],
    "position": [
      "center"
    ],
    "lang": [
      "en"
    ]
  },
  "tags": [
    "minimal"
  ],
  "repo": "https://github.com/PapaPeach/xhud",
  "hash": "765298bffce1598a475594cd03115df1ba6bb08c",
  "prerelease": true,
  "resources": [
    "xhud-banner",
    "ingame",
    "ingame-low",
    "scoreboard",
    "loadout",
    "stats",
    "customizations"
  ]
}

=== hexereii/BerryHUD/hud-data/garm3n-rex.json
{
  "name": "Garm3n Rex",
  "author": "Garm3n",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/GLD5e"
  },
  "repo": "https://github.com/Hypnootize/Garm3n-REX",
  "hash": "8916266392e7b9a748039fbd1286afd58896039f",
  "parent": "quakehud",
  "resources": [
    "garm3n-rex-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/ciba-hud.json
{
  "name": "cibahud",
  "author": "CibaCity",
  "social": {
    "steam_group": "cibascity",
    "album": "https://imgur.com/a/OoX4yAz"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/CibaCity/cibahud",
  "hash": "b71d09692301c33cb5e83db8e3e0c49060fcdfc4",
  "resources": [
    "ciba-hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/reverto-hud.json
{
  "name": "Reverto HUD",
  "author": "Starkie",
  "contributors": [
    "E-Thug",
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/iqXoZ"
  },
  "repo": "https://github.com/Hypnootize/Reverto-Hud",
  "hash": "d05eeece4945fd29adc4ce653e57169dc2c16adc",
  "resources": [
    "reverto-hud-banner"
  ]
}
