=== hexereii/BerryHUD/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "description": "Display name of your HUD",
      "type": "string"
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string"
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releaseDate": {
      "description": "Initial release date of the HUD",
      "type": "string"
    },
    "social": {
      "description": "Links to your social media profiles",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string"
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string"
        },
        "steam_group": {
          "description": "Your Steam group",
          "type": "string"
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string"
        },
        "discord": {
          "description": "Your Discord invite code, not the full URL",
          "type": "string"
        },
        "youtube": {
          "description": "Your YouTube channel (either /channel/id URL, @username or channel name)",
          "type": "string"
        },
        "twitch": {
          "description": "Your Twitch channel name",
          "type": "string"
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string"
        }
      }
    },
    "flags": {
      "description": "A list of boolean flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "1/1",
              "4/3",
              "5/4",
              "16/10",
              "16/9",
              "17/9",
              "21/9",
              "32/9"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      }
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repo": {
      "description": "GitHub repo web URL",
      "type": "string"
    },
    "hash": {
      "description": "Git commit hash of your current version (PR an update to this each time your HUD updates, and we will approve it)",
      "type": "string"
    },
    "prerelease": {
      "description": "If this is a prerelease/WIP HUD",
      "type": "boolean"
    },
    "verified": {
      "description": "For internal use only to enable some functionality. Do not set this yourself.",
      "type": "boolean"
    },
    "parent": {
      "description": "If this HUD is a slight edit of another, put its ID here. This will group the HUDs together.",
      "type": "string"
    },
    "resources": {
      "description": "A list of image names/YouTube videos. Images are automatically converted to webp, do not use extensions for uploaded images",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true
    }
  }
}

=== hexereii/BerryHUD/hud-data/colourhud.json
{
  "name": "ColourHUD",
  "author": "MrColour",
  "social": {
    "album": "https://imgur.com/a/g7KUgL9"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "streamer-mode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/mcolour/colourhud",
  "hash": "11e12149623f343924de90d4880362a0e8083ff0",
  "resources": [
    "colourhud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/bast-hud.json
{
  "name": "Bast HUD",
  "author": "b4stian",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "bastHUD",
    "album": "https://imgur.com/a/gDjCp"
  },
  "repo": "https://github.com/Hypnootize/Bast-Hud",
  "hash": "ac6d68ee4aa08491b00e25b44ee87f7934650a81",
  "resources": [
    "bast-hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/doshud.json
{
  "name": "dosHUD",
  "author": "Lavenfurr",
  "social": {
    "album": "https://github.com/LavenderTheGreat/dosHUD/issues/5"
  },
  "flags": [
    "materials"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "arena",
      "ad",
      "ctf",
      "cp",
      "koth",
      "pl",
      "plr",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/LavenderTheGreat/dosHUD",
  "hash": "569f4207b5ed155174415fa19fc4c633c3f9e8d4",
  "resources": [
    "doshud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/mhud.json
{
  "name": "mhud",
  "author": "Marblr",
  "social": {
    "album": "https://imgur.com/a/KVHaw"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "ad",
      "ctf",
      "cp",
      "koth",
      "mvm",
      "pl",
      "plr"
    ],
    "res": [
      "16/9"
    ]
  },
  "repo": "https://github.com/Marblr/mHUD",
  "hash": "ed89a10f71b8e82ad181558cfa4a5700229f3786",
  "resources": [
    "mhud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/ejp-hud.json
{
  "name": "EJP HUD",
  "author": "b4stian",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "ejphud",
    "album": "https://imgur.com/a/K8ZYc"
  },
  "repo": "https://github.com/Hypnootize/EJP-Hud",
  "hash": "15ccfb1aed9dd95818550f62026f9e8292c9fed7",
  "resources": [
    "ejp-hud-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/m0re-2009.json
{
  "name": "m0re 2009",
  "author": "m0re",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "album": "https://imgur.com/a/IcmXc"
  },
  "repo": "https://github.com/Hypnootize/m0re-Old",
  "hash": "97259d0a6f1ae41e1995c6113c1f94b7fb473b40",
  "parent": "m0rehud",
  "resources": [
    "m0re-2009-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/kn-old.json
{
  "name": "KN Old",
  "author": "Chippy",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "knhud",
    "album": "https://imgur.com/a/YblgN"
  },
  "repo": "https://github.com/Hypnootize/KN-Hud-Old",
  "hash": "b4c318bcdf02c06c9fed4820283bf8c667d85fb4",
  "parent": "kn-hud",
  "resources": [
    "kn-old-banner"
  ]
}

=== hexereii/BerryHUD/hud-data/omp-hud.json
{
  "name": "OMP HUD",
  "author": "OMP",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "tf2hud",
    "album": "https://imgur.com/a/mCoYj"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pl",
      "plr",
      "sd",
      "tc"
    ],
    "res": [
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/Hypnootize/OMP-Hud",
  "hash": "e051158f22ba1be5343eb9765451a037c8460589",
  "resources": [
    "omp-hud-banner"
  ]
}
